// Standardised rune tags so that the same rune can be compared across stones.
// Younger futhark (long-branch and short-twig variants) plus common medieval additions.
export const RUNE_TAGS: { tag: string; name: string; group: string }[] = [
  { tag: "ᚠ f", name: "fé", group: "Långkvist" },
  { tag: "ᚢ u", name: "úr", group: "Långkvist" },
  { tag: "ᚦ þ", name: "þurs", group: "Långkvist" },
  { tag: "ᚬ ą/o", name: "óss", group: "Långkvist" },
  { tag: "ᚱ r", name: "reið", group: "Långkvist" },
  { tag: "ᚴ k", name: "kaun", group: "Långkvist" },
  { tag: "ᚼ h", name: "hagall", group: "Långkvist" },
  { tag: "ᚾ n", name: "nauð", group: "Långkvist" },
  { tag: "ᛁ i", name: "íss", group: "Långkvist" },
  { tag: "ᛅ a", name: "ár", group: "Långkvist" },
  { tag: "ᛋ s", name: "sól", group: "Långkvist" },
  { tag: "ᛏ t", name: "týr", group: "Långkvist" },
  { tag: "ᛒ b", name: "bjarkan", group: "Långkvist" },
  { tag: "ᛘ m", name: "maðr", group: "Långkvist" },
  { tag: "ᛚ l", name: "lögr", group: "Långkvist" },
  { tag: "ᛦ R", name: "yr", group: "Långkvist" },
  { tag: "ᚽ h (kortkvist)", name: "hagall", group: "Kortkvist" },
  { tag: "ᚿ n (kortkvist)", name: "nauð", group: "Kortkvist" },
  { tag: "ᛆ a (kortkvist)", name: "ár", group: "Kortkvist" },
  { tag: "ᛌ s (kortkvist)", name: "sól", group: "Kortkvist" },
  { tag: "ᛐ t (kortkvist)", name: "týr", group: "Kortkvist" },
  { tag: "ᛙ m (kortkvist)", name: "maðr", group: "Kortkvist" },
  { tag: "ᛧ R (kortkvist)", name: "yr", group: "Kortkvist" },
  { tag: "ᛂ e (stungen)", name: "stungen i", group: "Stungna" },
  { tag: "ᚵ g (stungen)", name: "stungen k", group: "Stungna" },
  { tag: "ᛑ d (stungen)", name: "stungen t", group: "Stungna" },
  { tag: "ᛔ p", name: "stungen b", group: "Stungna" },
  { tag: "ᚤ y", name: "stungen u", group: "Stungna" },
  { tag: "Skiljetecken", name: "", group: "Övrigt" },
  { tag: "Ornamentik", name: "", group: "Övrigt" },
  { tag: "Kors", name: "", group: "Övrigt" },
];
